export default {
  name: 'asd',
  description: '',
  files: [],
  fields: [
    {
      id: '3b4bde3750ee49cb90c0a46062b4140b',
      name: 'qwe',
      description: null,
      type: 'Rich Text',
      default: null,
      required: false,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: 'bbc185fbc9084c71a2b7e1d1f0d5c32d',
      name: '<figure class="table"><table><tbody><tr><td>asd</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>asd</td><td>asdas</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>qweqwe</td><td>asdsad</td></tr></tbody></table></figure><p>test</p>',
      description: null,
      type: 'Static Rich Text',
      default: null,
      required: false,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '3dd4c633dfb845b1a7c2ca8cb5f413ef',
      name: null,
      description: null,
      type: 'Digital Signature',
      default: null,
      required: false,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: true,
      signatures: [
        {
          label: 'Non-AC Holder',
          required: false,
          signatureRole: null,
          signatureRoles: ['Non-AC Holder'],
        },
        {
          label: 'AC Holder',
          required: true,
          signatureRole: null,
          signatureRoles: ['AC Holder', 'Release Signatory'],
        },
      ],
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: 'ddef5ce619254e848efcae15e36e5b8e',
      name: 'qweqwe',
      description: null,
      type: 'Static Text',
      default: null,
      required: false,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: 'f4f927263b8b4df791e3e69803e22af5',
      name: null,
      description: null,
      type: 'Digital Signature',
      default: null,
      required: false,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: true,
      signatures: [
        {
          label: 'Non-AC Holder',
          required: false,
          signatureRole: null,
          signatureRoles: ['Non-AC Holder'],
        },
        {
          label: 'AC Holder',
          required: true,
          signatureRole: null,
          signatureRoles: ['AC Holder', 'Release Signatory'],
        },
      ],
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: 'b1e157a6e91e4e39b08d70605a7b78ff',
      name: 'qweqwe',
      description: null,
      type: 'Static Text',
      default: null,
      required: false,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '4727fbfd90934bd8bb9163a27f0091c1',
      name: 'qweqwe',
      description: null,
      type: 'Static Text',
      default: null,
      required: false,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: 'efbed9ebd9714232b0922d83ce23e2bd',
      name: null,
      description: null,
      type: 'Digital Signature',
      default: null,
      required: false,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: true,
      signatures: [
        {
          label: 'Non-AC Holder',
          required: false,
          signatureRole: null,
          signatureRoles: ['Non-AC Holder'],
        },
        {
          label: 'AC Holder',
          required: true,
          signatureRole: null,
          signatureRoles: ['AC Holder', 'Release Signatory'],
        },
      ],
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '8ec0395230884246978adddd6eabf8d1',
      name: 'asdasd',
      description: null,
      type: 'Radio Button Group',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: ['asd', 'asdasd'],
      files: [],
      hasDigitalSignature: true,
      signatures: [
        {
          label: 'Non-AC Holder',
          required: false,
          signatureRole: null,
          signatureRoles: ['Non-AC Holder'],
        },
        {
          label: 'AC Holder',
          required: true,
          signatureRole: null,
          signatureRoles: ['AC Holder', 'Release Signatory'],
        },
      ],
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: 'f8dcb103f3c64c72b0b0ea0a2a806594',
      name: 'asdasd',
      description: null,
      type: 'Radio Button Group',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: ['asd', 'asdasd'],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '9971cf93034e4f5fb652632b85fbc0b8',
      name: 'asdasd',
      description: null,
      type: 'Number',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '54416bb19de148e39d1982084b54c5dd',
      name: null,
      description: null,
      type: 'Static Text',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
  ],
  isTableSection: true,
  tableViewSpecs: {
    numberOfRows: 6,
    numberOfColumns: 2,
    rowHeights: null,
    colWidths: null,
    rowSpan: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    colSpan: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    visible: [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ],
  },
};
