export default {
  name: 'TEST_TABLE_TEST',
  description: '',
  files: [],
  fields: [
    {
      id: '9478fa770d9545d7a40bc931fbab8034',
      name: '1',
      description: null,
      type: 'Static Text',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '97d428948505460bbd428edcfafc19cd',
      name: null,
      description: null,
      type: 'Static Text',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '60af3d2b9dba44cd96661a77170e76d1',
      name: null,
      description: null,
      type: 'Static Text',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '6a04bcc7e473499a8f657903ef9dbb01',
      name: null,
      description: null,
      type: 'Static Text',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: 'bccf9cb797834954902e52c8c5cda835',
      name: '2',
      description: null,
      type: 'Static Text',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '2f130d5f18d749528f6a59900b42de63',
      name: null,
      description: null,
      type: 'Static Text',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '362d45c698654198aa27ed5fde2e51db',
      name: null,
      description: null,
      type: 'Static Text',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: 'b569e85116f9458f889332a396f82f2d',
      name: '6',
      description: null,
      type: 'Static Text',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
    {
      id: '5a4d06ad6a974903a7c9d6c1bd66f7e6',
      name: null,
      description: null,
      type: 'Static Text',
      default: null,
      required: true,
      minValue: null,
      maxValue: null,
      minValueInclusive: true,
      maxValueInclusive: true,
      absoluteMinValue: null,
      absoluteMaxValue: null,
      absoluteMinValueInclusive: true,
      absoluteMaxValueInclusive: true,
      minLength: null,
      maxLength: null,
      maxSelectableOptions: null,
      uom: null,
      validationHint: '',
      absoluteValidationHint: '',
      options: [],
      files: [],
      hasDigitalSignature: false,
      signatures: null,
      isNewOrAmended: false,
      amendmentRemarks: null,
    },
  ],
  isTableSection: true,
  tableViewSpecs: {
    numberOfRows: 3,
    numberOfColumns: 3,
    rowSpan: [2, 1, 1, 1, 1, 1, 1, 1, 1],
    colSpan: [1, 1, 1, 1, 2, 1, 1, 1, 1],
    visible: [true, true, true, false, true, false, true, true, true],
  },
};
