export const dummy_form_data = {
  successful: true,
  data: {
    authoredForm: {
      id: 1609,
      formName: 'test_table_krisna_lagi_create',
      formType: 'CRR Form',
      status: 2,
      initialIssueNumber: 2,
      latestPublishedVersion: null,
      reviewedBy: null,
      approvedBy: null,
      authoredBy: 'Engineer #1',
      rejectReason: null,
      headerFields: [
        {
          id: 'crrFormType',
          name: 'CRR Form Type',
          description: 'Desc',
          fieldType: 'crrFormTypeSelection',
          isEditableByAuthor: true,
          isEditableByResponder: false,
          isRequiredFromAuthor: true,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: false,
          options: {},
          value:
            '{"id":14,"sequence":1,"formTypeCode":"QAD003-02C1","formType":"Test Record"}',
        },
        {
          id: 'crr',
          name: 'CRR Number',
          description: 'Desc',
          fieldType: 'crrSelection',
          isEditableByAuthor: true,
          isEditableByResponder: true,
          isRequiredFromAuthor: true,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: true,
          options: {},
          value: '40/CRR/236',
        },
        {
          id: 'partNos',
          name: 'Part Number(s)',
          description: '',
          fieldType: 'partNumbersSelection',
          isEditableByAuthor: true,
          isEditableByResponder: false,
          isRequiredFromAuthor: true,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: true,
          options: {},
          value: '10-62008-37',
        },
        {
          id: 'manualRef',
          name: 'Manual Reference',
          description: '',
          fieldType: 'manualRefSelection',
          isEditableByAuthor: true,
          isEditableByResponder: false,
          isRequiredFromAuthor: false,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: false,
          options: {},
          value:
            '[{"manualNo":"Manual #2","revNo":"015","revDate":"2018-06-15T00:00:00","pubNo":"1","pubNoFormatted":"CMM1","revisionStatus":"015, dated: 15 Jun 2018","manualFormatted":"Manual #2 (ref: 015, dated: 15 Jun 2018)"}]',
        },
        {
          id: 'suggestedPartNos',
          name: 'Higher Assembly',
          description: '',
          fieldType: 'suggestedPartNosSelection',
          isEditableByAuthor: true,
          isEditableByResponder: false,
          isRequiredFromAuthor: false,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: false,
          options: {},
          value: null,
        },
      ],
      sections: [
        {
          name: '1',
          description: '',
          files: [],
          fields: [
            {
              id: '90b10d872bbb4ff48b79d1d427a6d287',
              name: 'asd',
              description: null,
              type: 'Static Text',
              default: null,
              required: true,
              minValue: null,
              maxValue: null,
              minValueInclusive: true,
              maxValueInclusive: true,
              absoluteMinValue: null,
              absoluteMaxValue: null,
              absoluteMinValueInclusive: true,
              absoluteMaxValueInclusive: true,
              minLength: null,
              maxLength: null,
              maxSelectableOptions: null,
              uom: null,
              validationHint: '',
              absoluteValidationHint: '',
              options: [],
              files: [],
              hasDigitalSignature: false,
              signatures: null,
              isNewOrAmended: false,
              amendmentRemarks: null,
            },
            {
              id: 'ba14e99cef654b408df1a1b3a1aee8f0',
              name: 'zxc',
              description: null,
              type: 'Static Text',
              default: null,
              required: true,
              minValue: null,
              maxValue: null,
              minValueInclusive: true,
              maxValueInclusive: true,
              absoluteMinValue: null,
              absoluteMaxValue: null,
              absoluteMinValueInclusive: true,
              absoluteMaxValueInclusive: true,
              minLength: null,
              maxLength: null,
              maxSelectableOptions: null,
              uom: null,
              validationHint: '',
              absoluteValidationHint: '',
              options: [],
              files: [],
              hasDigitalSignature: false,
              signatures: null,
              isNewOrAmended: false,
              amendmentRemarks: null,
            },
            {
              id: '29c5f092b6b24e9ab6c3ad7e96928ac1',
              name: null,
              description: null,
              type: 'Static Text',
              default: null,
              required: true,
              minValue: null,
              maxValue: null,
              minValueInclusive: true,
              maxValueInclusive: true,
              absoluteMinValue: null,
              absoluteMaxValue: null,
              absoluteMinValueInclusive: true,
              absoluteMaxValueInclusive: true,
              minLength: null,
              maxLength: null,
              maxSelectableOptions: null,
              uom: null,
              validationHint: '',
              absoluteValidationHint: '',
              options: [],
              files: [],
              hasDigitalSignature: false,
              signatures: null,
              isNewOrAmended: false,
              amendmentRemarks: null,
            },
            {
              id: '861ff4618d1f46bf8e46fbc70f986a31',
              name: null,
              description: null,
              type: 'Static Text',
              default: null,
              required: true,
              minValue: null,
              maxValue: null,
              minValueInclusive: true,
              maxValueInclusive: true,
              absoluteMinValue: null,
              absoluteMaxValue: null,
              absoluteMinValueInclusive: true,
              absoluteMaxValueInclusive: true,
              minLength: null,
              maxLength: null,
              maxSelectableOptions: null,
              uom: null,
              validationHint: '',
              absoluteValidationHint: '',
              options: [],
              files: [],
              hasDigitalSignature: false,
              signatures: null,
              isNewOrAmended: false,
              amendmentRemarks: null,
            },
            {
              id: '8d121dce53ee4fbd9a9da600b2ba8f73',
              name: 'asd',
              description: null,
              type: 'Static Text',
              default: null,
              required: true,
              minValue: null,
              maxValue: null,
              minValueInclusive: true,
              maxValueInclusive: true,
              absoluteMinValue: null,
              absoluteMaxValue: null,
              absoluteMinValueInclusive: true,
              absoluteMaxValueInclusive: true,
              minLength: null,
              maxLength: null,
              maxSelectableOptions: null,
              uom: null,
              validationHint: '',
              absoluteValidationHint: '',
              options: [],
              files: [],
              hasDigitalSignature: false,
              signatures: null,
              isNewOrAmended: false,
              amendmentRemarks: null,
            },
            {
              id: '1a009d3c8d4d41c78cac589c6686bae2',
              name: null,
              description: null,
              type: 'Static Text',
              default: null,
              required: true,
              minValue: null,
              maxValue: null,
              minValueInclusive: true,
              maxValueInclusive: true,
              absoluteMinValue: null,
              absoluteMaxValue: null,
              absoluteMinValueInclusive: true,
              absoluteMaxValueInclusive: true,
              minLength: null,
              maxLength: null,
              maxSelectableOptions: null,
              uom: null,
              validationHint: '',
              absoluteValidationHint: '',
              options: [],
              files: [],
              hasDigitalSignature: false,
              signatures: null,
              isNewOrAmended: false,
              amendmentRemarks: null,
            },
            {
              id: '6ab120bfc1bc4981a5ba2f4531c4b9fd',
              name: null,
              description: null,
              type: 'Static Text',
              default: null,
              required: true,
              minValue: null,
              maxValue: null,
              minValueInclusive: true,
              maxValueInclusive: true,
              absoluteMinValue: null,
              absoluteMaxValue: null,
              absoluteMinValueInclusive: true,
              absoluteMaxValueInclusive: true,
              minLength: null,
              maxLength: null,
              maxSelectableOptions: null,
              uom: null,
              validationHint: '',
              absoluteValidationHint: '',
              options: [],
              files: [],
              hasDigitalSignature: false,
              signatures: null,
              isNewOrAmended: false,
              amendmentRemarks: null,
            },
            {
              id: '918e39fc9bff470ebdd9bd1e6a86cf99',
              name: null,
              description: null,
              type: 'Static Text',
              default: null,
              required: true,
              minValue: null,
              maxValue: null,
              minValueInclusive: true,
              maxValueInclusive: true,
              absoluteMinValue: null,
              absoluteMaxValue: null,
              absoluteMinValueInclusive: true,
              absoluteMaxValueInclusive: true,
              minLength: null,
              maxLength: null,
              maxSelectableOptions: null,
              uom: null,
              validationHint: '',
              absoluteValidationHint: '',
              options: [],
              files: [],
              hasDigitalSignature: false,
              signatures: null,
              isNewOrAmended: false,
              amendmentRemarks: null,
            },
            {
              id: 'b338b2e28aea40bc905078678382fcdc',
              name: null,
              description: null,
              type: 'Static Text',
              default: null,
              required: true,
              minValue: null,
              maxValue: null,
              minValueInclusive: true,
              maxValueInclusive: true,
              absoluteMinValue: null,
              absoluteMaxValue: null,
              absoluteMinValueInclusive: true,
              absoluteMaxValueInclusive: true,
              minLength: null,
              maxLength: null,
              maxSelectableOptions: null,
              uom: null,
              validationHint: '',
              absoluteValidationHint: '',
              options: [],
              files: [],
              hasDigitalSignature: false,
              signatures: null,
              isNewOrAmended: false,
              amendmentRemarks: null,
            },
          ],
          isTableSection: true,
          tableViewSpecs: {
            numberOfRows: 3,
            numberOfColumns: 3,
            rowHeights: ['0px', '0px', '0px'],
            colWidths: [
              '33.333333333333336%',
              '33.333333333333336%',
              '33.333333333333336%',
            ],
            rowSpan: [2, 1, 1, 1, 1, 2, 1, 1, 1],
            colSpan: [1, 1, 1, 1, 1, 1, 1, 1, 1],
            visible: [true, true, true, false, true, true, true, true, false],
          },
        },
      ],
      isActive: true,
      relatedUnpublishedForms: [
        {
          id: 227,
          formName: 'QAD002-02ABCD',
          formType: 'CRR Form',
          status: 2,
          newVersionHasImpact: false,
        },
      ],
      lastModified: '2024-10-08T14:52:21.8224301',
      approvedOn: null,
      reviewedOn: null,
      ndtIssueNumber: null,
      ndtRevStatus: null,
      newVersionHasImpact: false,
      rwwsIndex: null,
      aircraftType: null,
      isRWWSIndexPage: false,
      rwwsIndexDescription: null,
    },
    formTypeSpecs: {
      name: 'CRR Form',
      headerFields: [
        {
          id: 'crrFormType',
          name: 'CRR Form Type',
          description: 'Desc',
          fieldType: 'crrFormTypeSelection',
          isEditableByAuthor: true,
          isEditableByResponder: false,
          isRequiredFromAuthor: true,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: false,
          options: {},
          value:
            '{"id":14,"sequence":1,"formTypeCode":"QAD003-02C1","formType":"Test Record"}',
        },
        {
          id: 'crr',
          name: 'CRR Number',
          description: 'Desc',
          fieldType: 'crrSelection',
          isEditableByAuthor: true,
          isEditableByResponder: true,
          isRequiredFromAuthor: true,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: true,
          options: {},
          value: '40/CRR/236',
        },
        {
          id: 'partNos',
          name: 'Part Number(s)',
          description: '',
          fieldType: 'partNumbersSelection',
          isEditableByAuthor: true,
          isEditableByResponder: false,
          isRequiredFromAuthor: true,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: true,
          options: {},
          value: '10-62008-37',
        },
        {
          id: 'manualRef',
          name: 'Manual Reference',
          description: '',
          fieldType: 'manualRefSelection',
          isEditableByAuthor: true,
          isEditableByResponder: false,
          isRequiredFromAuthor: false,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: false,
          options: {},
          value:
            '[{"manualNo":"Manual #2","revNo":"015","revDate":"2018-06-15T00:00:00","pubNo":"1","pubNoFormatted":"CMM1","revisionStatus":"015, dated: 15 Jun 2018","manualFormatted":"Manual #2 (ref: 015, dated: 15 Jun 2018)"}]',
        },
        {
          id: 'suggestedPartNos',
          name: 'Higher Assembly',
          description: '',
          fieldType: 'suggestedPartNosSelection',
          isEditableByAuthor: true,
          isEditableByResponder: false,
          isRequiredFromAuthor: false,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: false,
          options: {},
          value: null,
        },
      ],
      formTypeLabels: {
        fieldName: 'Manual Ref Page/Para',
        validationHint: 'Design Spec',
        absoluteValidationHint: 'Tolerance Limit',
        signatureRole: 'Certification',
      },
      headerFieldsIndexedFields: [
        {
          id: 'crr',
          name: 'CRR Number',
          description: 'Desc',
          fieldType: 'crrSelection',
          isEditableByAuthor: true,
          isEditableByResponder: true,
          isRequiredFromAuthor: true,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: true,
          options: {},
          value: '40/CRR/236',
        },
        {
          id: 'partNos',
          name: 'Part Number(s)',
          description: '',
          fieldType: 'partNumbersSelection',
          isEditableByAuthor: true,
          isEditableByResponder: false,
          isRequiredFromAuthor: true,
          isRequiredFromResponder: false,
          minLength: null,
          maxLength: null,
          minValue: null,
          maxValue: null,
          validationHint: '',
          showInFormListPage: true,
          options: {},
          value: '10-62008-37',
        },
      ],
      signature: {
        roles: [
          'Non-AC Holder',
          'AC Holder',
          'Release Signatory',
          'D1-MPI',
          'D1-FPI',
          'D1-ECI',
          'D1-UI',
          'D1-NE',
          'D1-BI',
          'D2',
          'D2-Cd',
          'D2-Cr',
          'D2-M',
          'D2-Ni',
          'D2-P',
          'D2-SP',
        ],
      },
    },
    openUserAction: null,
    workflowInstanceId: null,
  },
  errorMessage: '',
};
